sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint bluepy
language: python
script:
- flake8 switchbot --max-line-length=120
- pylint switchbot --max-line-length=120
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: PuBVoRFUIcT4+mVVq/GiFs9nEcfggeVPN8U8DHyruy7mr84Ceuncke1S1hQk4x0Lfa/cIozEx0OIcbTmIUXB3mVfRX07XQGMi1KAYg6fEXaiKOyfBftX5f2DzyRoLw37Xfb0HC0M1YJiyG5k8WIp1QWYu+3EtUvrH7kRALz4tbT8A3Xc/Q4u/+5WUCIp0FzGj4qCbzrvpatXuqD+nWRh81TgtF2867/F2xfcJ0LSAuLOL+1bWGhy48CvJfoZl/rAMWaPZ/V6FkeSvSQHosh57mQraCZ+DhHkObE+/3yrA4DEQFF1rZI3wndmvmgwSIxmoshbS3SBcTSXfOoBwYCpqWpehW0nCaO5gDzBctmeicsOOIhGfLukWOoE5F4TQ6GiCHPQJkn9QTHHFrtq060GIFvhaIadYiftztoph8fQmgZQmJ/Xl8T/o93CGwYXrzkKh0mEIXqtRQrmpALsOec5UqxA/OvnfcPSiE3D1K8+ex5N1fiem+8NXRYo/SSMKZS54rTEqldaD8pdmMvdbALHtcE639MSK5gIT5wRbEWIYEPM+NyCXbM73BKmLijr5/az7GkP1U9td8/fUujSZch9WPyz5JSSENr98tO0zsVpC0bmOZsLtzrxN0ejAC1IpK/davx0igwuE6PegjRRo3OxxlrX7dYJOkIZtqVTghk67Zg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/pySwitchbot
